### ISSUE TITLE
Plugin broken

### ISSUE THREAD

**Issue by Skeeve** [antonnyman/vscode-go-sql-highlight#1]
When I save my program containing:

```go
		rows, err = tx.Query(ctx, /* sql */ `
			UPDATE clientips AS ips
			SET test_start = CASE -- keep test date, when the previous failed
```

the linter converts it to

```go
		rows, err = tx.Query(ctx /* sql */, `
			UPDATE clientips AS ips
			SET test_start = CASE -- keep test date, when the previous failed
```

and so the highlighting is gone.

**Comment by Skeeve** [comment]
This should fix it:

https://github.com/antonnyman/vscode-go-sql-highlight/blob/92f829bf4c8d14b44e6a27249e907e905eb60cd9/syntaxes/go-sql-highlight.json#L7

```json
"begin": "\\s*+(/\\* [sS][qQ][lL] \\*/)\\s*,?\\s*(`)",
```

**Comment by Skeeve** [comment]
P.S. Changing my code to

```go
		rows, err = tx.Query(ctx,
			/* sql */ `
			UPDATE clientips AS ips
			SET test_start = CASE -- keep test date, when the previous failed
```

Also worked… I think it's a matter of personal taste.

**Comment by antonnyman** [comment]
Hi @Skeeve!

Thank you for submitting an issue, sorry I haven't responded.

I don't use this plugin daily anymore but I'm glad someone uses it!

Do you mind making a pull request with your changes?
